services:
  front:
    build:
      context: ./frontend
      dockerfile: prod.dockerfile
      args:
        - USER_ID=1000
        - GROUP_ID=1000
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=production
    env_file:
      - ./frontend/production.env
    depends_on:
      - back
  back:
    build:
      context: ./backend
      dockerfile: prod.dockerfile
      args:
        - USER_ID=1000
        - GROUP_ID=1000
    expose:
      - 3000
    environment:
      - NODE_ENV=production
    env_file:
      - ./backend/production.env
    depends_on:
      - postgres
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx:/etc/nginx
      - ./frontend/dist:/usr/share/nginx/html
    ports:
      - 80:80
      - 443:443
    depends_on:
      - front
      - back
  postgres:
    image: "postgres:17"
    env_file:
      - ./backend/.env
    ports:
      - 7000:5432
    volumes:
      - es_app:/var/lib/postgresql/data
volumes:
  es_app: