services:
  nginx:
    build:
      context: ./frontend
      dockerfile: prod.dockerfile
      args:
        - USER_ID=1000
        - GROUP_ID=1000
    environment:
      - NODE_ENV=production
    ports:
      - 80:80
      - 443:443
    env_file:
      - ./frontend/production.env
    depends_on:
      - back
  back:
    build:
      context: ./backend
      dockerfile: prod.dockerfile
      args:
        - USER_ID=1000
        - GROUP_ID=1000
    expose:
      - 3000
    environment:
      - NODE_ENV=production
    env_file:
      - ./backend/production.env
volumes:
  es_app: